# Generated by Django 3.0.5 on 2020-05-21 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 21)),
        ),
    ]
